"""alt posts

Revision ID: 67a777d8a14a
Revises: 369000765d0f
Create Date: 2017-02-22 17:16:36.373374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a777d8a14a'
down_revision = '369000765d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###
