"""update Post

Revision ID: ae9387586fdf
Revises: b2bd5e75eb40
Create Date: 2017-03-31 11:36:42.009322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9387586fdf'
down_revision = 'b2bd5e75eb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img')
    # ### end Alembic commands ###
